# Generated by Django 3.2.6 on 2021-08-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashback_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_document', models.CharField(max_length=11)),
                ('customer_document_validated', models.CharField(max_length=255)),
                ('cashback_message', models.CharField(max_length=255)),
                ('cashback_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_document', models.CharField(max_length=11)),
            ],
        ),
    ]
