# Generated by Django 3.2.6 on 2021-08-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashback_api',
            name='customer_document_validated',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
